name: togolist
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_maps_flutter: ^1.2.0
  location: ^2.3.5
  provider: ^4.3.3
  firebase_core: ^0.4.0+9
#  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.14
  cloud_firestore: ^0.12.9+5
  backdrop: ^0.5.2
  google_maps_webservice: ^0.0.19
  flutter_slidable: ^0.5.7
  geodesy: ^0.3.2
  font_awesome_flutter: ^8.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand/Quicksand-Medium.ttf
#        - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
#          style: bold
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
#        - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
#          style: bold
